import './Rating.css';
import { useLoadScripts } from '../utilities/use_scripts';

function Rating() {
  useLoadScripts([
    '/static_js/show_page_loader.js',
    '/static_js/url_to_server.js',
    '/static_js/get_user_data.js',
    '/static_js/rating_script.js',
    '/static_js/show_page.js'
  ])

  return (
    <div className="background">
    <div className="rating_wrapper">
    <button className="back_to_home">
        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#5f6368"><path d="m313-440 224 224-57 56-320-320 320-320 57 56-224 224h487v80H313Z"/></svg>
    </button>
        <h1>Rating</h1>
    <div className="table_wrapper">
    <table>
        <thead>
            <tr>
                <th>Avatar</th>
                <th>Login</th>
                <th>Victories</th>
                <th>Battles</th>
                <th>KPD</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>

            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>3</td>
                <td>10</td>
                <td>30%</td>
            </tr>
        </tbody>
    </table>
    </div>
    </div>
    </div>
  );
}

export default Rating;